[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "pip install playwright",
  "playwright install chromium --with-deps",
  "npm install"
]

[phases.build]
cmds = ["npm run build:css", "python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
